#
# Copyright 2021, Seqera Labs, S.L. All Rights Reserved.
#

## DNAnexus quickstart
clean:
	rm -rf build
	
dx-pull-nf:
	mkdir -p build/nextflow-dx/resources/usr/bin
	mkdir -p build/nextflow-dx/resources/opt/nextflow
	NXF_VER=21.04.1-edge NXF_HOME=build/nextflow-dx/resources/opt/nextflow bash -c 'curl get.nextflow.io | bash'
	mv nextflow build/nextflow-dx/resources/usr/bin/nextflow
	rm -rf build/nextflow-dx/resources/opt/nextflow/tmp

dx-core-pack:
	mkdir -p build/nextflow-dx/resources/usr/bin
	cd ../nextflow && rm -rf build && make packCore
	cp ../nextflow/build/releases/nextflow-* build/nextflow-dx/resources/usr/bin/nextflow

dx-plugin-pack: 
	cd ../nf-xpack && make assemble
	mkdir -p build/nextflow-dx/resources/opt/nextflow/plugins
	cp -r ../nf-xpack/build/plugins/xpack-dnanexus-* build/nextflow-dx/resources/opt/nextflow/plugins
	rm build/nextflow-dx/resources/opt/nextflow/plugins/*.zip

dx-build: dx-core-pack dx-plugin-pack
	# copy dnanexus template
	cp -r app/* build/nextflow-dx/
	dx build build/nextflow-dx -f
	# info
	echo "Run with: dx run nextflow-dx --watch -y"

dx-run: dx-build
	dx run nextflow-dx --watch -y
