name: DNAnexus XPACK
on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Nextflow App Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install dxpy and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https openssh-server python3 python3-pip python3-venv make
          pip3 install setuptools wheel
          pip3 install dxpy
      - name: Run tests
        env:
          AUTH_TOKEN: ${{ secrets.DX_AUTH_TOKEN }}
          NXF_XPACK_LICENSE: ${{ secrets.NXF_XPACK_LICENSE }}
        run: |
          set -x
          export PATH="$PATH:$HOME/.local/bin"
          dx login --noprojects --token $AUTH_TOKEN
          dx select 'Nextflow App'
          APP_ID=$(make dx-pack dx-build | grep '"id":' | awk '{ gsub(/"|}/, "", $2); print $2 }')
          dx run $APP_ID --watch -y -ilicense=$NXF_XPACK_LICENSE -iargs="-with-docker"
